module.exports = {
 "verification": "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY",
 "description": "Majo.exe - Discord's multifunctional bot, contains moderation, fun, music, economics and NSFW commands.",
 "twitter": "@majonezexe",
 "mobile": "false",
 "image": "https://igorkowalczyk.github.io/lib/favicon/favicon.jpg",
 "server": "https://discord.gg/bVNNHuQ",
 "authorwebsite": "https://igorkowalczyk.github.io",
 "author": "Igor Kowalczyk (Majonez.exe#3957)",
 "github": "igorkowalczyk",
 "domain": process.env.DOMAIN,
 "google_analitics": process.env.ANALYTICS,
 "token": process.env.TOKEN,
 "clientSecret": process.env.SECRET,
 "sessionSecret": process.env.SESSION_SECRET,
 "port": process.env.PORT,
 "prefix": process.env.PREFIX,
 "dashboard": process.env.DASHBOARD,
 "newstitle": "<a:error:759354037803024395> Warning",
 "news":  "*05-01-2021* - Bot is currently under rebuilding, data in commands, configuration, money is NOT SAVED! Planned completion time is 31-01-2021, be patient... \n *09-01-2021* - Log system is broken and may not work, We are working to fix it. Thanks"
}
