module.exports = {
 "verification": "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY",
 "description": "Majo.exe - Discord bot for Fun, Memes, Images, Giveaway, Economy, Anime and NSFW! Majo serve over 100 commands!",
 "twitter": "@majonezexe",
 "mobile": "false",
 "image": "banner.jpg",
 "server": "https://discord.gg/bVNNHuQ",
 "authorwebsite": "https://igorkowalczyk.github.io",
 "status": "https://stats.uptimerobot.com/5lVA7t0zZq",
 "author": "Igor Kowalczyk (Majonez.exe#3957)",
 "ownerid": "440200028292907048",
 "github": "igorkowalczyk",
 "repo": "majobot",
 "domain": process.env.DOMAIN,
 "google_analitics": process.env.ANALYTICS,
 "clientSecret": process.env.SECRET,
 "id": process.env.ID,
 "port": process.env.PORT,
 "sessionSecret": process.env.SESSION_SECRET,
 "prefix": process.env.PREFIX,
 "scopes": "bot",
 "premissions": "4294967287",
 "youtube": process.env.YOUTUBE,
 "dashboard": process.env.DASHBOARD,
 "brainid": process.env.BRAINID,
 "brainkey": process.env.BRAINKEY,
 "cookies": process.env.COOKIES,
 "statuschannel": "712024850675531786",
 "suggestionschannel": "838092194530852884",
 "newstitle": "<a:success:759354039242063903> Good news!",
 "news":  "Majo.exe is waiting for verification because it is on over 75 servers. We are sorry if you can't add Majo.exe to your server now, it will be possible soon. Thank you for your support. Stay tuned!"
}
