module.exports = {
 // Main config
 author: "Igor Kowalczyk (Majonez.exe#3957)",
 aurhor_website: "https://igorkowalczyk.github.io",
 owner_id: "440200028292907048",
 description: "Majo.exe - Discord bot for Fun, Memes, Images, Giveaway, Economy, Anime and NSFW! Majo serve over 100 commands!",
 support_server: "https://discord.gg/bVNNHuQ",
 status: "https://majoexe.instatus.com",
 twitter: "@majonezexe",
 github: "igorkowalczyk",
 github_repo: "majobot",
 about_bot: "... Soon!",
 about_dev: "... Soon!",
 donation_perks: "",
 patreon: "igorkowalczyk",
 ko_fi: "igorkowalczyk",
 buymeacoffee: "rkjha",
 open_collective: "igorkowalczyk",
 scopes: "bot%20applications.commands",
 permissions: "4294967287",
 suggestions_channel: "838092194530852884",
 bot_news_title: "<:success:860884617820110909> Good news!",
 news: "Majo.exe - Discord.js v13 Beta!",
 brainid: process.env.BRAINID,
 brainkey: process.env.BRAINKEY,
 prefix: process.env.PREFIX,
 youtube: process.env.YOUTUBE,
 id: process.env.ID,
 advanved_logging: false,

 // Dashboard config
 domain: process.env.DOMAIN,
 certs: false,
 localhost: false,
 privacy_policy_page: true,
 google_analitics: process.env.ANALYTICS,
 client_secret: process.env.SECRET,
 port: process.env.PORT,
 session_secret: process.env.SESSION_SECRET,
 dashboard: process.env.DASHBOARD,
 cookies: process.env.COOKIES,
 mobile_support: "false",
 image: "banner.jpg",
 verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY",
};
