name: Lint

on: [push, pull_request]

jobs:
 lint:
  timeout-minutes: 15
  name: ESLint
  runs-on: ubuntu-latest
  env:
   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
   TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  strategy:
   fail-fast: false
   matrix:
    node: ["lts/*"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v7
   - name: 🔩 Setup PNPM
     uses: pnpm/action-setup@v4
     with:
      standalone: true
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v6
     with:
      node-version: ${{ matrix.node }}
      cache: "pnpm"
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: 🚀 Run ESLint
     run: pnpm lint
